// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8qGjJS2_vBUpiklpXoTX4gW59U613yAE',
    appId: '1:860310823445:web:8a36594bd2923b78bc641c',
    messagingSenderId: '860310823445',
    projectId: 'talkzy-chat-app-8d8e5',
    authDomain: 'talkzy-chat-app-8d8e5.firebaseapp.com',
    storageBucket: 'talkzy-chat-app-8d8e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5V1wg4xJSNo3S63QB3dn-VHHWC1YQeNM',
    appId: '1:860310823445:android:5a67c1ff51b709d6bc641c',
    messagingSenderId: '860310823445',
    projectId: 'talkzy-chat-app-8d8e5',
    storageBucket: 'talkzy-chat-app-8d8e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG9noJ9D2iKCNJxYWqXg1l3y2GNpJux8A',
    appId: '1:860310823445:ios:b030ff049aa89dc5bc641c',
    messagingSenderId: '860310823445',
    projectId: 'talkzy-chat-app-8d8e5',
    storageBucket: 'talkzy-chat-app-8d8e5.firebasestorage.app',
    iosBundleId: 'com.example.talkzyBeta1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG9noJ9D2iKCNJxYWqXg1l3y2GNpJux8A',
    appId: '1:860310823445:ios:b030ff049aa89dc5bc641c',
    messagingSenderId: '860310823445',
    projectId: 'talkzy-chat-app-8d8e5',
    storageBucket: 'talkzy-chat-app-8d8e5.firebasestorage.app',
    iosBundleId: 'com.example.talkzyBeta1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8qGjJS2_vBUpiklpXoTX4gW59U613yAE',
    appId: '1:860310823445:web:9e16012f116b86d6bc641c',
    messagingSenderId: '860310823445',
    projectId: 'talkzy-chat-app-8d8e5',
    authDomain: 'talkzy-chat-app-8d8e5.firebaseapp.com',
    storageBucket: 'talkzy-chat-app-8d8e5.firebasestorage.app',
  );
}
